version: '3.4'

services:
  corebanking.api:
    image: ${DOCKER_REGISTRY-}corebankingapi
    build:
      context: .
      dockerfile: Apps/CoreBanking.API/Dockerfile

  postgres:
#    container_name: postgres_container
#    image: postgres:15.0-alpine
    build:
      context: .
      dockerfile: SupplementaryProjects/HyperScalePostgres/HyperScalePostgres/Dockerfile